Added age slider to form 1
mhsvictoria/mhsvictoria_ios pull request #1
Opened 2020-09-12 22:27 UTC by kentblock

Added a basic age slider to the first form, still needs to be styled.

2020-09-13 00:27 UTC, rcallan13 requested changes
We need to set up a string file and a string localization scheme. I will put those into the development branch. What you have done looks good. It takes a while to get used to the swift shortcuts. I have added some comments with respect to using var get and set, etc. My syntax might not be perfect but it should work something like what I commented on.

2020-09-13 00:27 UTC, rcallan13 commented on mhsvictoria_ios/Form1ViewController.swift
> +    func setAgeFormLabel() {
In Swift, if you use a didSet you don't need an accessor. You can take the functionality from here and put it directly into the didSet. For example, 
var age = 0 {
        didSet {
             ageFormLabel.text = "I am \(age) years old..."}
      }
}
However, in this case I would use the get/set associated with the variable. For example,
// say you had a permiter value that was going to be displayed
var perimeter: Double {
    get {
        if let sideLength = UserDefaults.standard.value(perimKey) {
        return  3.0 * sideLength
       }
       return 0
    }
    set {
        sideLength = newValue / 3.0
       let text = String.format("side.length".localized, age)
       myLabel.text = text
       UserDefaults.standard.setValue(newValue, forKey: perimKey)
    }
}

put the body of the load in the get and the save in the set.

2020-09-13 00:27 UTC, rcallan13 commented on mhsvictoria_ios/Form1ViewController.swift
> +        ageFormLabel.text = "I am \(age) years old..."
For the String values, put these into a String resource so that translation is easily done. I have checked an example into the development branch. It uses the typical data type expressions like '%d' for Int, etc.

2020-09-13 00:27 UTC, rcallan13 commented on mhsvictoria_ios/Form1ViewController.swift
> +    func saveAge() {
You can inline this right in the variable. Same for loadAge.

2020-09-13 19:34 UTC, kentblock commented
Thanks for the feedback Ron! I have made the changes, let me know if they are correct.

2020-09-14 19:04 UTC, rcallan13 commented
Thanks for making the changes.

2020-09-14 19:04 UTC, merged